# Generated by Django 5.2.7 on 2025-10-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Дом')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задолженность поставщику')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factories_supplied', to='elements.factory', verbose_name='Поставщик (завод)')),
                ('products', models.ManyToManyField(blank=True, to='elements.product', verbose_name='Продукты')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Дом')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задолженность поставщику')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='elements.product', verbose_name='Продукты')),
                ('supplier_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_networks_supplied', to='elements.factory', verbose_name='Поставщик (завод)')),
                ('supplier_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networks_supplied', to='elements.retailnetwork', verbose_name='Поставщик (сеть)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Дом')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задолженность поставщику')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ie_supplied_by_factory', to='elements.factory', verbose_name='Поставщик (завод)')),
                ('supplier_ie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ie_supplied_by_ie', to='elements.individualentrepreneur', verbose_name='Поставщик (ИП)')),
                ('products', models.ManyToManyField(blank=True, to='elements.product', verbose_name='Продукты')),
                ('supplier_retail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ie_supplied_by_retail', to='elements.retailnetwork', verbose_name='Поставщик (сеть)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
