# Generated by Django 5.2.7 on 2025-10-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Завод', 'verbose_name_plural': 'Заводы'},
        ),
        migrations.AlterModelOptions(
            name='individualentrepreneur',
            options={'verbose_name': 'Индивидуальный предприниматель', 'verbose_name_plural': 'Индивидуальные предприниматели'},
        ),
        migrations.AlterModelOptions(
            name='retailnetwork',
            options={'verbose_name': 'Розничная сеть', 'verbose_name_plural': 'Розничные сети'},
        ),
    ]
