# Generated by Django 5.2.7 on 2025-10-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_alter_factory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
