# Generated by Django 5.2.7 on 2025-10-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='elements.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='elements.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='elements.product', verbose_name='Продукты'),
        ),
    ]
